package co.com.capacitacion2.capacitacion2clase3;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Clase5Tarea1Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void clase5Tarea1() {
    driver.get("https://www.marca.com/ciclismo/tour-francia/clasificacion/etapa-20.html");
    driver.findElement(By.id("selectweb")).click();
    {
      WebElement dropdown = driver.findElement(By.id("selectweb"));
      dropdown.findElement(By.xpath("//option[. = 'Selecciona etapa']")).click();
    }
    {
      WebElement dropdown = driver.findElement(By.id("selectweb"));
      dropdown.findElement(By.xpath("//option[. = 'Etapa 20']")).click();
    }
    driver.findElement(By.id("selectweb")).click();
    driver.findElement(By.cssSelector(".content-item:nth-child(1) .ue-table-ranking__tr:nth-child(1) .ue-table-ranking__cyclist-name")).click();
  }
}
